### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by ufoxp** [sheldonth/ios-cmake#11]
This repo needs clear licensing statement. MIT license would do fine? Is ios.cmake toolchain your creation or is it derived from something?

**Comment by flandr** [comment]
https://github.com/sheldonth/ios-cmake/blob/master/LICENSE ?

**Comment by ufoxp** [comment]
Ha! So I'm blind it seems :)

**Comment by ufoxp** [comment]
But then again none of the files have copyright / license notice. So distribution in source code form is kind of bothersome because "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." so I would have to put this LICENSE file somewhere where it is clear what the license covers...

**Comment by sheldonth** [comment]
Perhaps there's some legal precedent to having a license notice on the top of every file, but whatever it is is surely less than the distraction and added effort of reading past that block of repeated data in each source file. With the aim of instruction in mind (it's inherently a design pattern), having each file being nothing but source and inline comments is preferable.
The MIT-License-at-the-repo-root is well trodden in mobile software and I don't know that it's unclear what is and isn't covered in such a way.

**Comment by ufoxp** [comment]
It becomes less clear when it is put into code base with different license... it is just a hasle to document what is under what license if it is not in source code files themselves...

**Comment by sheldonth** [comment]
What file header would you propose?

**Comment by flandr** [comment]
This is not a new problem in software. Stick a provision like "Portions of this sofware are based on (foo) (copyright notice bar)" in your license if you include it.
