### ISSUE TITLE
Issue with switching this to build C only framework

### ISSUE THREAD

**Issue by dillonykyang** [sheldonth/ios-cmake#21]
did a quick mod to change the `Foo.hh` to `Foo.h` and remove the classes with a `int foo(void);` definition and `printf("foo");` implementation. Compiling the framework is working, however the app throws a MACH-O linker error when built with xcode.

```
Undefined symbols for architecture x86_64:
  "foo()", referenced from:
      -[CppInterface init] in CppInterface.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by sheldonth** [comment]
That error means that the object file isn't linked into the program. You have a definition for foo() but are missing the object. What's your goal? I don't think you should need any chances to write C code in place of C++ but I haven't tested that concept.

**Comment by dillonykyang** [comment]
Thanks - I have this resolved - the objective-cpp bridge forced the compiler to use the c++ compiler.

**Comment by sheldonth** [comment]
Excellent!
